import './globals.css'
import { Inter } from 'next/font/google'
import Nav from "@/app/components/Nav";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Share Thoughts',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
  )
}
